---
title: "stl_lead_inequity"
author: "Melannie Moreno Rolon"
format: html
editor: visual
---

```{r}
#libraries
library(janitor)
library(tidyverse)
library(ggplot2)
```

```{r}
stl_lead <- read_csv(here::here("data", "stl_blood_lead.csv")) 
stl_lead <- stl_lead %>% clean_names()
```

```{r}
#Summary statistics
summary(stl_lead)

#exploration of data
dim(stl_lead)
names(stl_lead)
```

```{r}
#create a new data frame
stl_lead_prop <- stl_lead |> 
  mutate(prop_white = (white/total_pop)*100)

stl_lead_prop
names(stl_lead_prop)
dim(stl_lead_prop)
```

```{r}
#scatterplot graph
stl_lead_plot <- ggplot(data = stl_lead_prop, aes(x = pct_elevated, y = prop_white)) +
  geom_point(aes(color = prop_white), show.legend = FALSE) +
  theme_minimal() + 
  labs(title = "Percentage with elevated blood lead levels versus the Percent of each census tract identifying as white", 
       x = "Percent of Census Tract Identifying as White",
       y = "Percent of Children With Elevated Blood Levels")

stl_lead_plot

#export scatterplot
ggsave(here::here("figs", "stl_lead_plot.png"), height = 5, width = 6)
```

```{r}
#histogram
pct_elevated_hist <- ggplot(data = stl_lead_prop, aes(x = pct_elevated)) +
  geom_histogram(aes(color = "black"), show.legend = FALSE) +
  theme_minimal() + 
  labs(title = "Percentage of children in each census tract with elevated blood lead levels", 
       x = "Blood lead levels (%)")

pct_elevated_hist

ggsave(here::here("figs", "pct_elevated_hist.png"), height = 5, width = 6)
```

